#define IO_GET_ADD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x666, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

typedef struct _KERNEL_ADD_REQUEST
{
	int Operand1;
	int Operand2;
	int Result;

} KERNEL_ADD_REQUEST, * P_KERNEL_ADD_REQUEST;